#ifndef __GVEC_MODULAR_H__
#define __GVEC_MODULAR_H__

#include "gvec_general.h"

GVEC_APPLY_TYPESET( GVEC_H_DECLARE, __GVTEST_TYPESET_INTV );
GVEC_APPLY_TYPESET( GVEC_H_DECLARE, __GVTEST_TYPESET_INTR );

#endif /*__GVEC_MODULAR_H__*/
