#ifndef __GVEC_MODULAR_H__
#define __GVEC_MODULAR_H__

#include "gvec_general.h"

__GVT_TYPESET_TO_ARGS( GVEC_H_DECLARE, __GVTEST_TYPESET_INTV );
__GVT_TYPESET_TO_ARGS( GVEC_H_DECLARE, __GVTEST_TYPESET_INTR );

#endif /*__GVEC_MODULAR_H__*/
