#ifndef __GVEC_STATIC_H__
#define __GVEC_STATIC_H__

#include "gvec_general.h"

GVEC_APPLY_TYPESET( GVEC_INSTANTIATE, __GVTEST_TYPESET_INTV );
GVEC_APPLY_TYPESET( GVEC_INSTANTIATE, __GVTEST_TYPESET_INTR );

#endif /*__GVEC_STATIC_H__*/
