#ifndef __GVEC_STATIC_H__
#define __GVEC_STATIC_H__

#include "gvec_general.h"

__GVT_TYPESET_TO_ARGS( GVEC_INSTANTIATE, __GVTEST_TYPESET_INTV );
__GVT_TYPESET_TO_ARGS( GVEC_INSTANTIATE, __GVTEST_TYPESET_INTR );

#endif /*__GVEC_STATIC_H__*/
