#ifndef __GVEC_STATIC_H__
#define __GVEC_STATIC_H__

#include "gvec_general.h"

GENA_APPLY_TYPESET( GVEC_INSTANTIATE, __GVECTEST_TYPESET_INT_VAL );
GENA_APPLY_TYPESET( GVEC_INSTANTIATE, __GVECTEST_TYPESET_STRUCT_REF );
GENA_APPLY_TYPESET( GVEC_INSTANTIATE_EX, __GVECTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET( GVEC_INSTANTIATE_EX, __GVECTEST_TYPESET_EX_ARRAY_BUF );

#endif /*__GVEC_STATIC_H__*/
