#include "gvec_modular.h"

GENA_APPLY_TYPESET( GVEC_C_DEFINE, ZZ_GVECTEST_TYPESET_INT_VAL );
GENA_APPLY_TYPESET( GVEC_C_DEFINE, ZZ_GVECTEST_TYPESET_STRUCT_PTR );
GENA_APPLY_TYPESET( GVEC_C_DEFINE_EX, ZZ_GVECTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET( GVEC_C_DEFINE_EX, ZZ_GVECTEST_TYPESET_EX_ARRAY_BUF );
