#ifndef ZZ_GVEC_STATIC_H_IG
#define ZZ_GVEC_STATIC_H_IG

#include "gvec_general.h"

GENA_APPLY_TYPESET( GVEC_INSTANTIATE, ZZ_GVECTEST_TYPESET_INT_VAL );
GENA_APPLY_TYPESET( GVEC_INSTANTIATE, ZZ_GVECTEST_TYPESET_STRUCT_REF );
GENA_APPLY_TYPESET( GVEC_INSTANTIATE_EX, ZZ_GVECTEST_TYPESET_EX_STRING_PTR );
GENA_APPLY_TYPESET( GVEC_INSTANTIATE_EX, ZZ_GVECTEST_TYPESET_EX_ARRAY_ARR );

#endif /* ZZ_GVEC_STATIC_H_IG */
