#ifndef __GVEC_MODULAR_H__
#define __GVEC_MODULAR_H__

#include "gvec_general.h"

GENA_APPLY_TYPESET( GVEC_H_DECLARE, __GVECTEST_TYPESET_INTV );
GENA_APPLY_TYPESET( GVEC_H_DECLARE, __GVECTEST_TYPESET_INTR );

#endif /*__GVEC_MODULAR_H__*/
