#ifndef __GVEC_MODULAR_H__
#define __GVEC_MODULAR_H__

#include "gvec_general.h"

GENA_APPLY_TYPESET( GVEC_H_DECLARE, __GVECTEST_TYPESET_INT_VAL );
GENA_APPLY_TYPESET( GVEC_H_DECLARE, __GVECTEST_TYPESET_STRUCT_REF );
GENA_APPLY_TYPESET( GVEC_H_DECLARE_EX, __GVECTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET( GVEC_H_DECLARE_EX, __GVECTEST_TYPESET_EX_ARRAY_BUF );

#endif /*__GVEC_MODULAR_H__*/
