#ifndef ZZ_GTSET_MODULAR_H_IG
#define ZZ_GTSET_MODULAR_H_IG

#include "gtset_general.h"

GENA_APPLY_TYPESET( GTSET_H_DECLARE, ZZ_GTSETTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GTSET_H_DECLARE, ZZ_GTSETTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GTSET_H_DECLARE, ZZ_GTSETTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GTSET_H_DECLARE_EX, ZZ_GTSETTEST_TYPESET_EX_STRING_PTR );
GENA_APPLY_TYPESET( GTSET_H_DECLARE_EX, ZZ_GTSETTEST_TYPESET_EX_ARRAY_ARR );

#endif /* ZZ_GTSET_MODULAR_H_IG */
