#include "gtset_modular.h"

GENA_APPLY_TYPESET( GTSET_C_DEFINE, ZZ_GTSETTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GTSET_C_DEFINE, ZZ_GTSETTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GTSET_C_DEFINE, ZZ_GTSETTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GTSET_C_DEFINE_EX, ZZ_GTSETTEST_TYPESET_EX_STRING_PTR );
GENA_APPLY_TYPESET( GTSET_C_DEFINE_EX, ZZ_GTSETTEST_TYPESET_EX_ARRAY_ARR );
