#ifndef ZZ_GMAP_STATIC_H_IG
#define ZZ_GMAP_STATIC_H_IG

#include "gmap_general.h"

GENA_APPLY_TYPESET( GMAP_INSTANTIATE, ZZ_GMAPTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE, ZZ_GMAPTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE, ZZ_GMAPTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE_EX, ZZ_GMAPTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE_EX, ZZ_GMAPTEST_TYPESET_EX_ARRAY_BUF );

#endif /* ZZ_GMAP_STATIC_H_IG */
