#include "gmap_modular.h"

GENA_APPLY_TYPESET( GMAP_C_DEFINE, __GMAPTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GMAP_C_DEFINE, __GMAPTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_C_DEFINE, __GMAPTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_C_DEFINE_EX, __GMAPTEST_TYPESET_EX_STRING_BUF );
