#ifndef __GMAP_MODULAR_H__
#define __GMAP_MODULAR_H__

#include "gmap_general.h"

GENA_APPLY_TYPESET( GMAP_H_DECLARE, __GMAPTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GMAP_H_DECLARE, __GMAPTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_H_DECLARE, __GMAPTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_H_DECLARE_EX, __GMAPTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET( GMAP_H_DECLARE_EX, __GMAPTEST_TYPESET_EX_ARRAY_BUF );

#endif /*__GMAP_MODULAR_H__*/
