#ifndef __GMAP_STATIC_H__
#define __GMAP_STATIC_H__

#include "gmap_general.h"

GENA_APPLY_TYPESET( GMAP_INSTANTIATE, __GMAPTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE, __GMAPTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE, __GMAPTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE_EX, __GMAPTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET( GMAP_INSTANTIATE_EX, __GMAPTEST_TYPESET_EX_ARRAY_BUF );

#endif /*__GMAP_STATIC_H__*/
