#include "gtmap_modular.h"

GENA_APPLY_TYPESET( GTMAP_C_DEFINE, ZZ_GTMAPTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET( GTMAP_C_DEFINE, ZZ_GTMAPTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET( GTMAP_C_DEFINE, ZZ_GTMAPTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET( GTMAP_C_DEFINE_EX, ZZ_GTMAPTEST_TYPESET_EX_STRING_PTR );
GENA_APPLY_TYPESET( GTMAP_C_DEFINE_EX, ZZ_GTMAPTEST_TYPESET_EX_ARRAY_ARR );
