#ifndef ZZ_GTMAP_STATIC_H_IG
#define ZZ_GTMAP_STATIC_H_IG

#include "gtmap_general.h"

GENA_APPLY_TYPESET(
  GTMAP_INSTANTIATE, ZZ_GTMAPTEST_TYPESET_NAIVE_INT_VAL );
GENA_APPLY_TYPESET(
  GTMAP_INSTANTIATE, ZZ_GTMAPTEST_TYPESET_MEMCMP_STRUCT_REF );
GENA_APPLY_TYPESET(
  GTMAP_INSTANTIATE, ZZ_GTMAPTEST_TYPESET_CALLBACK_STRUCT_REF );
GENA_APPLY_TYPESET(
  GTMAP_INSTANTIATE_EX, ZZ_GTMAPTEST_TYPESET_EX_STRING_BUF );
GENA_APPLY_TYPESET(
  GTMAP_INSTANTIATE_EX, ZZ_GTMAPTEST_TYPESET_EX_ARRAY_BUF );

#endif /* ZZ_GTMAP_STATIC_H_IG */
